import {
  JoButton,
  JoButtonGroup,
  JoIcon,
  JoCollapse,
  JoCollapseItem,
  JoAlert,
  JoTooltip,
  JoDropdown,
  JoDropdownItem,
  JoPopconfirm,
  JoMessage,
  JoNotification,
  JoInput,
  JoMessageBox,
  JoLoading,
  JoSwitch,
  JoSelect,
  JoOption,
} from "@jonny-element/components";

import type { Plugin } from "vue";

export default [
  JoButton,
  JoButtonGroup,
  JoIcon,
  JoCollapse,
  JoCollapseItem,
  JoAlert,
  JoTooltip,
  JoDropdown,
  JoDropdownItem,
  JoPopconfirm,
  JoMessage,
  JoNotification,
  JoInput,
  JoMessageBox,
  JoLoading,
  JoSwitch,
  JoSelect,
  JoOption,
] as Plugin[];//导出数组
